import { describe, it, expect } from "vitest";
import { handleGenerateHtaccess } from "../tools/tier3/htaccess-generator.js";

describe("generate_htaccess", () => {
  // ---- Positive cases ----

  it("generates empty .htaccess with only comment", () => {
    const result = handleGenerateHtaccess({});
    expect(result.content).toContain("# .htaccess generated by ZERONOVA LAB MCP Server");
    expect(result.validation.isValid).toBe(true);
  });

  it("generates .htaccess with redirect rules", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [
        { from: "/old-page", to: "/new-page", statusCode: 301 },
        { from: "/blog/old", to: "/blog/new", statusCode: 302 },
      ],
    });
    expect(result.content).toContain("RewriteEngine On");
    expect(result.content).toContain("RewriteRule ^old-page$ /new-page [R=301,L]");
    expect(result.content).toContain("RewriteRule ^blog/old$ /blog/new [R=302,L]");
    expect(result.validation.isValid).toBe(true);
  });

  it("generates .htaccess with 307 and 308 status codes", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [
        { from: "/temp", to: "/target", statusCode: 307 },
        { from: "/perm", to: "/final", statusCode: 308 },
      ],
    });
    expect(result.content).toContain("[R=307,L]");
    expect(result.content).toContain("[R=308,L]");
  });

  it("defaults to 301 when no statusCode is specified", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old", to: "/new" }],
    });
    expect(result.content).toContain("[R=301,L]");
  });

  it("generates .htaccess with gzip compression", () => {
    const result = handleGenerateHtaccess({
      compressionEnabled: true,
    });
    expect(result.content).toContain("<IfModule mod_deflate.c>");
    expect(result.content).toContain("AddOutputFilterByType DEFLATE text/html");
    expect(result.content).toContain("AddOutputFilterByType DEFLATE application/javascript");
    expect(result.content).toContain("</IfModule>");
    expect(result.validation.isValid).toBe(true);
  });

  it("generates .htaccess with cache control", () => {
    const result = handleGenerateHtaccess({
      cacheControl: [
        { extension: "css", maxAge: 86400 },
        { extension: "js", maxAge: 604800 },
        { extension: "png", maxAge: 2592000 },
      ],
    });
    expect(result.content).toContain("<IfModule mod_expires.c>");
    expect(result.content).toContain("ExpiresActive On");
    expect(result.content).toContain('<FilesMatch "\\.css$">');
    expect(result.content).toContain("access plus 86400 seconds");
    expect(result.content).toContain("access plus 604800 seconds");
    expect(result.content).toContain("</IfModule>");
    expect(result.validation.isValid).toBe(true);
  });

  it("generates .htaccess with force HTTPS", () => {
    const result = handleGenerateHtaccess({
      forceHttps: true,
    });
    expect(result.content).toContain("RewriteEngine On");
    expect(result.content).toContain("RewriteCond %{HTTPS} off");
    expect(result.content).toContain("https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]");
    expect(result.validation.isValid).toBe(true);
  });

  it("generates .htaccess with trailing slash removal", () => {
    const result = handleGenerateHtaccess({
      removeTrailingSlash: true,
    });
    expect(result.content).toContain("RewriteEngine On");
    expect(result.content).toContain("RewriteCond %{REQUEST_FILENAME} !-d");
    expect(result.content).toContain("RewriteRule ^(.*)/$ /$1 [R=301,L]");
    expect(result.validation.isValid).toBe(true);
  });

  it("only includes one RewriteEngine On with multiple features", () => {
    const result = handleGenerateHtaccess({
      forceHttps: true,
      removeTrailingSlash: true,
      redirectRules: [{ from: "/old", to: "/new" }],
    });
    const rewriteEngineCount = (result.content.match(/RewriteEngine On/g) ?? []).length;
    expect(rewriteEngineCount).toBe(1);
    expect(result.validation.isValid).toBe(true);
  });

  it("generates complete .htaccess with all options", () => {
    const result = handleGenerateHtaccess({
      forceHttps: true,
      removeTrailingSlash: true,
      redirectRules: [{ from: "/old", to: "/new", statusCode: 301 }],
      compressionEnabled: true,
      cacheControl: [{ extension: "css", maxAge: 86400 }],
    });
    expect(result.content).toContain("Force HTTPS");
    expect(result.content).toContain("Remove trailing slash");
    expect(result.content).toContain("Redirect rules");
    expect(result.content).toContain("Enable gzip compression");
    expect(result.content).toContain("Cache control");
    expect(result.validation.isValid).toBe(true);
  });

  // ---- Injection prevention ----

  it("rejects backtick injection in redirect path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old`whoami`", to: "/new" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
    expect(result.validation.issues[0]).toContain("dangerous pattern");
    expect(result.content).not.toContain("whoami");
  });

  it("rejects $() command substitution in redirect path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old", to: "/new$(cat /etc/passwd)" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
    expect(result.validation.issues[0]).toContain("dangerous pattern");
  });

  it("rejects ${} variable substitution in redirect path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old${PATH}", to: "/new" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
  });

  it("rejects %{ENV:VAR} server variable injection", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old%{ENV:SECRET}", to: "/new" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
  });

  it("rejects newline injection in path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old\nRewriteRule ^(.*)$ https://evil.com/$1 [R=301,L]", to: "/new" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
  });

  it("rejects null byte injection in path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old\x00", to: "/new" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
  });

  // ---- Negative cases ----

  it("throws on more than 100 redirect rules", () => {
    const rules = Array.from({ length: 101 }, (_, i) => ({
      from: `/old-${i}`,
      to: `/new-${i}`,
    }));
    expect(() => handleGenerateHtaccess({ redirectRules: rules })).toThrow(
      "redirectRules exceeds maximum of 100 items",
    );
  });

  it("reports issue for invalid status code", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old", to: "/new", statusCode: 404 }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
    expect(result.validation.issues[0]).toContain("invalid statusCode");
  });

  it("reports issue for missing from path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "", to: "/new" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
  });

  it("reports issue for missing to path", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old", to: "" }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
  });

  it("reports issue for cache maxAge exceeding limit", () => {
    const result = handleGenerateHtaccess({
      cacheControl: [{ extension: "css", maxAge: 99999999 }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
    expect(result.validation.issues[0]).toContain("maxAge must be 0-31536000");
  });

  it("escapes special regex chars in file extension for FilesMatch", () => {
    const result = handleGenerateHtaccess({
      cacheControl: [{ extension: "js.map", maxAge: 86400 }],
    });
    expect(result.content).toContain("js\\.map");
    expect(result.validation.isValid).toBe(true);
  });

  it("rejects path-like extension value", () => {
    const result = handleGenerateHtaccess({
      cacheControl: [{ extension: "../etc/passwd", maxAge: 86400 }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
    expect(result.validation.issues[0]).toContain("invalid extension");
    expect(result.content).not.toContain("passwd");
  });

  it("rejects extension with spaces", () => {
    const result = handleGenerateHtaccess({
      cacheControl: [{ extension: "j s", maxAge: 86400 }],
    });
    expect(result.validation.issues.length).toBeGreaterThan(0);
    expect(result.validation.issues[0]).toContain("invalid extension");
  });

  it("handles from path with trailing slash in redirect", () => {
    const result = handleGenerateHtaccess({
      redirectRules: [{ from: "/old/path/", to: "/new/path/" }],
    });
    expect(result.content).toContain("^old/path/$");
    expect(result.validation.isValid).toBe(true);
  });
});
