/**
 * Tier 3: robots.txt generator
 * Generates a valid robots.txt file from structured input.
 *
 * Checklist 2-D:
 * - Output validation: line format check (User-agent:, Disallow:, Allow:, Sitemap: only)
 * - Injection prevention: no raw user input embedded without validation
 * - No browser-dependent APIs
 */

const MAX_PATHS = 100;
const MAX_PATH_LENGTH = 2048;
const MAX_SITEMAP_URL_LENGTH = 2048;

/** Valid robots.txt directive prefixes */
const VALID_DIRECTIVES = [
  "User-agent:",
  "Disallow:",
  "Allow:",
  "Sitemap:",
  "Crawl-delay:",
] as const;

export interface RobotsTxtInput {
  sitemapUrl?: string;
  disallowPaths?: string[];
  allowPaths?: string[];
  userAgent?: string;
  crawlDelay?: number;
}

export interface RobotsTxtResult {
  content: string;
  lineCount: number;
  validation: {
    isValid: boolean;
    issues: string[];
  };
}

/**
 * Sanitize a path for robots.txt — remove control characters and ensure it starts with /
 */
function sanitizePath(path: string): string {
  // Remove control characters
  const cleaned = path.replace(/[\x00-\x1f\x7f]/g, "");
  // Ensure path starts with /
  if (!cleaned.startsWith("/") && cleaned !== "") {
    return "/" + cleaned;
  }
  return cleaned;
}

/**
 * Validate generated robots.txt content — all lines must match valid directive patterns.
 */
function validateRobotsTxt(content: string): { isValid: boolean; issues: string[] } {
  const issues: string[] = [];
  const lines = content.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === "" || line.startsWith("#")) continue;

    const isValidDirective = VALID_DIRECTIVES.some(
      (d) => line.startsWith(d),
    );
    if (!isValidDirective) {
      issues.push(`Line ${i + 1}: unrecognized directive "${line.slice(0, 50)}"`);
    }
  }

  return { isValid: issues.length === 0, issues };
}

export function handleGenerateRobotsTxt(input: RobotsTxtInput): RobotsTxtResult {
  const issues: string[] = [];
  // Sanitize userAgent — remove control characters to prevent newline injection
  // (e.g., "Googlebot\nDisallow: *" would inject arbitrary directives)
  const userAgent = (input.userAgent ?? "*").replace(/[\x00-\x1f\x7f]/g, "");
  const disallowPaths = input.disallowPaths ?? [];
  const allowPaths = input.allowPaths ?? [];

  // Runtime validation (checklist 2-A)
  if (disallowPaths.length > MAX_PATHS) {
    throw new Error(`disallowPaths exceeds maximum of ${MAX_PATHS} items (received ${disallowPaths.length})`);
  }
  if (allowPaths.length > MAX_PATHS) {
    throw new Error(`allowPaths exceeds maximum of ${MAX_PATHS} items (received ${allowPaths.length})`);
  }
  if (input.sitemapUrl && input.sitemapUrl.length > MAX_SITEMAP_URL_LENGTH) {
    throw new Error(`sitemapUrl exceeds maximum of ${MAX_SITEMAP_URL_LENGTH} characters`);
  }
  if (input.sitemapUrl && !input.sitemapUrl.startsWith("http://") && !input.sitemapUrl.startsWith("https://")) {
    throw new Error("sitemapUrl must start with http:// or https://");
  }
  if (input.sitemapUrl && /[\x00-\x1f\x7f]/.test(input.sitemapUrl)) {
    throw new Error("sitemapUrl must not contain control characters");
  }
  if (input.crawlDelay !== undefined && (input.crawlDelay < 0 || input.crawlDelay > 60)) {
    throw new Error("crawlDelay must be between 0 and 60 seconds");
  }

  const lines: string[] = [];
  lines.push("# robots.txt generated by ZERONOVA LAB MCP Server");
  lines.push("");
  lines.push(`User-agent: ${userAgent}`);

  // Add Disallow paths
  for (const path of disallowPaths) {
    if (path.length > MAX_PATH_LENGTH) {
      issues.push(`Disallow path truncated (exceeded ${MAX_PATH_LENGTH} chars): ${path.slice(0, 50)}...`);
      continue;
    }
    const sanitized = sanitizePath(path);
    lines.push(`Disallow: ${sanitized}`);
  }

  // Add Allow paths
  for (const path of allowPaths) {
    if (path.length > MAX_PATH_LENGTH) {
      issues.push(`Allow path truncated (exceeded ${MAX_PATH_LENGTH} chars): ${path.slice(0, 50)}...`);
      continue;
    }
    const sanitized = sanitizePath(path);
    lines.push(`Allow: ${sanitized}`);
  }

  // Add Crawl-delay
  if (input.crawlDelay !== undefined && input.crawlDelay > 0) {
    lines.push(`Crawl-delay: ${input.crawlDelay}`);
  }

  // Add Sitemap
  if (input.sitemapUrl) {
    lines.push("");
    lines.push(`Sitemap: ${input.sitemapUrl}`);
  }

  lines.push("");
  const content = lines.join("\n");

  // Output validation (checklist 2-D)
  const validation = validateRobotsTxt(content);
  if (validation.issues.length > 0) {
    issues.push(...validation.issues);
  }

  return {
    content,
    lineCount: content.split("\n").length,
    validation: {
      isValid: validation.isValid,
      issues,
    },
  };
}
